name: Renew Server

on:
  workflow_dispatch:
  schedule:
#    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run renewal script
      run: python main.py renew

    - name: Upload success screenshot
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: renewal-screenshot
        path: renewal_success.png
        if-no-files-found: ignore

    - name: Upload error screenshot
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: renewal-screenshot
        path: renewal_error.png
        if-no-files-found: ignore
