# .github/workflows/main.yml

name: Solve reCAPTCHA and Upload Result

on:
  workflow_dispatch:

jobs:
  solve-captcha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CAPTCHA solver script
        env:
          # Use the API key you stored in GitHub secrets
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          # --- FIX IS HERE ---
          # Provide the GitHub token to avoid API rate limiting when downloading the webdriver
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py recaptcha

      - name: Upload final screenshot
        uses: actions/upload-artifact@v4
        with:
          name: captcha-result-screenshot
          path: final_result.png
